name: sketch_pad
description: An experimental redux of the DartPad UI.
publish_to: 'none'

environment:
  sdk: ^3.2.0

dependencies:
  codemirror: any
  collection: any
  dartpad_shared: any
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fluttering_phrases: ^1.0.0
  go_router: ^12.1.0
  http: any
  intl: any
  json_annotation: ^4.8.1
  pointer_interceptor: ^0.9.0
  provider: ^6.0.0
  split_view: ^3.2.0
  url_launcher: any
  url_strategy: any
  vtable: ^0.4.0
  messages: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: any
  build_runner: 2.4.6
  build_runner_core: 7.2.10
  flutter_messages: ^0.1.0
  messages_serializer: ^0.1.0
  messages_builder: ^0.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/dart_logo_128.png
    - assets/flutter_logo_192.png
    - lib/l10n/en.json
    - lib/l10n/de.json

dependency_overrides:
  dartpad_shared:
    path: ../dartpad_shared
