language: dart
install:
  - gem install coveralls-lcov
dart:
  # Keep this value aligned with min SDK value in pubspec.yaml and FROM line of Dockerfile
  - "2.6.0"
  # TODO(devoncarew): commented out due to
  # https://github.com/dart-lang/dart-pad/issues/1002
  #- dev

# Speed up builds by using containerization. Disable this if you need to use
# sudo in your scripts.
sudo: false

branches:
  only: [master, uf]
before_script:
  - git submodule init
  - git submodule update
  - export PATH=$PATH:$PWD/flutter/bin
  - flutter doctor
  - flutter config --enable-web
  - flutter precache --web --no-android --no-ios --no-linux --no-windows --no-macos --no-fuchsia
script: ./travis.sh
