name: dart_services
publish_to: none

environment:
  # Keep SDK aligned with .travis.yml and FROM line of Dockerfile
  sdk: ^2.6.0

dependencies:
  _discoveryapis_commons: 0.1.9
  analyzer: ^0.38.0
  analysis_server_lib: ^0.1.4
  appengine: ^0.10.3
  args: ^1.5.2
  bazel_worker: ^0.1.23
  crypto: ^2.0.0
  dartis: ^0.3.0
  http: ^0.12.0
  logging: ^0.11.0
  path: ^1.6.2
  shelf: ^0.7.0
  rpc: ^0.6.2
  uuid: ^2.0.0
  yaml: ^2.1.15
  quiver: ^2.0.3

dev_dependencies:
  discoveryapis_generator: ^0.9.11
  async: ^2.2.0
  codemirror: ^0.5.6
  coverage: ^0.13.0
  grinder: ^0.8.0
  pedantic: ^1.8.0
  synchronized: ^2.1.0
  test: ^1.6.4
  tuneup: ^0.3.6

executables:
  services: null
