name: dart_pad
author: Dart Team <misc@dartlang.org>
description: The UI client for a web based interactive Dart service.
homepage: https://github.com/dart-lang/dart-pad
environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  codemirror: ^0.5.0
  # TODO(jcollins-g): return to haikunator pub package after it is
  # published with https://github.com/Atrox/haikunatordart/pull/1
  #haikunator: ^0.1.0
  haikunator:
    path: third_party/pkg/haikunatordart/
  http: '>=0.11.1 <0.13.0'
  logging: '>=0.9.0 <0.12.0'
  markdown: ^2.0.0
  meta: ^1.1.7
  octicons_css: ^0.0.1
  primer_css: ^0.0.1
  protobuf: ^1.0.1
  route_hierarchical:
    path: third_party/pkg/route.dart/
  split: ^0.0.6
  html_unescape: ^1.0.0
  sass_builder: ^2.1.0
  mdc_web: ^0.5.0-pre
  yaml: ^2.2.0

dev_dependencies:
  build_runner: any
  build_test: any
  build_web_compilers: any
  collection: ^1.14.10
  git: ^1.0.0
  grinder: ^0.8.0
  pedantic: ^1.9.0
  shelf: ^0.7.5
  shelf_static: ^0.2.8
  test: ^1.3.4
  tuneup: any
