name: dart_pad
description: The UI client for a web based interactive Dart service.
publish_to: none

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  async: ^2.9.0
  checked_yaml: ^2.0.0
  codemirror: ^0.7.6+5.65.5
  collection: ^1.16.0
  encrypt: ^5.0.1
  fluttering_phrases: ^0.4.0
  html_unescape: ^2.0.0
  http: ^0.13.0
  js: ^0.6.4
  json_annotation: ^4.5.0
  logging: ^1.0.0
  markdown: ^7.0.1
  mdc_web: ^0.6.0
  meta: ^1.8.0
  path: ^1.8.0
  protobuf: ^2.1.0
  pub_semver: ^2.1.0
  # ^2.1.5 is no longer compatible with our overridden sass version
  # https://github.com/dart-lang/dart-pad/issues/2388
  sass_builder: 2.1.4
  shelf: ^1.3.0
  shelf_static: ^1.1.0
  split:
    path: third_party/pkg/split/
  stream_transform: ^2.0.0
  yaml: ^3.1.1

dev_dependencies:
  build_runner: ^2.1.11
  build_test: ^2.0.0
  build_web_compilers: ^3.0.0
  git: ^2.0.0
  grinder: ^0.9.1
  json_serializable: ^6.0.1
  lints: ^2.0.0
  test: ^1.21.1
  webdriver: ^3.0.2

# waiting for the next material-components-web release.
# Once released, it will need to be rolled into package:mdc_web.
#
# https://github.com/material-components/material-components-web/pull/7158
# https://github.com/dart-lang/dart-pad/issues/2388
dependency_overrides:
  sass: 1.32.10
