name: dart_services
publish_to: none

environment:
  sdk: ^2.19.0

dependencies:
  analysis_server_lib: ^0.2.4
  analyzer: ^5.10.0
  args: ^2.4.0
  bazel_worker: ^1.0.2
  convert: ^3.1.1
  crypto: ^3.0.2
  encrypt: ^5.0.1
  http: ^0.13.5
  logging: ^1.1.1
  meta: ^1.9.1
  path: ^1.8.3
  protobuf: ^2.1.0
  quiver: ^3.2.1
  resp_client: ^1.2.0
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  yaml: ^3.1.1

dev_dependencies:
  angel3_mock_request: ^7.0.1
  async: ^2.11.0
  build_runner: ^2.3.3
  coverage: ^1.6.3
  dart_flutter_team_lints: ^1.0.0
  grinder: ^0.9.3
  package_config: ^2.1.0
  shelf_router_generator: ^1.0.5
  synchronized: ^3.0.1
  test: ^1.24.2
  test_descriptor: ^2.0.1

executables:
  services: null
