name: dart_services
author: Dart Team <misc@dartlang.org>
description: The server backend for a web based interactive Dart service.
homepage: https://github.com/dart-lang/dart-services

environment:
  sdk: '>=2.0.0-dev.54 <2.0.0'

dependencies:
  analysis_server_lib: ^0.1.2+2
  appengine: 0.4.0-flex.alpha.0+3
  archive: '>=1.0.19 <1.1.0'
  args: '>=0.12.0 <0.14.0'
  crypto: ^2.0.0
  logging: '>=0.9.0 <0.12.0'
  path: ^1.3.0
  shelf: ^0.6.0
  shelf_cors: ^0.2.0
  rpc: ^0.5.0
  uuid: ^0.5.0
  yaml: ^2.0.0

dev_dependencies:
  _discoveryapis_commons: any
  browser: any
  codemirror: ^0.4.0
  grinder: ^0.8.0
  http: any
  test: ^0.12.0

executables:
  services: null
