name: dart_services
publish_to: none

environment:
  # Keep SDK aligned with .travis.yml and FROM line of Dockerfile
  sdk: ^2.10.0

dependencies:
  analyzer: ^0.39.17
  analysis_server_lib: ^0.1.4
  appengine: ^0.12.0
  args: ^1.6.0
  bazel_worker: ^0.1.23
  crypto: ^2.0.0
  dartis: ^0.5.0
  http: ^0.12.0
  logging: ^0.11.0
  meta: ^1.1.8
  path: ^1.6.2
  protobuf: ^1.0.1
  quiver: ^2.0.3
  shelf: ^0.7.5
  shelf_router: ^0.7.0+1
  uuid: ^2.0.0
  yaml: ^2.1.15

dev_dependencies:
  async: ^2.2.0
  build_runner: ^1.10.0
  codemirror: ^0.5.6
  coverage: ^0.14.0
  grinder: ^0.8.0
  mock_request: ^1.0.7
  pedantic: ^1.9.0
  shelf_router_generator: ^0.7.0+1
  synchronized: ^2.1.0
  test: ^1.6.4
  tuneup: ^0.3.6

executables:
  services: null
