name: dart_pad
author: Dart Team <misc@dartlang.org>
description: The UI client for a web based interactive Dart service.
homepage: https://github.com/dart-lang/dart-pad
environment:
  sdk: '>=2.10.4 <3.0.0'

dependencies:
  codemirror: ^0.6.0-0
  fluttering_phrases: ^0.3.1
  http: '>=0.12.2 <0.13.0'
  json_annotation: ^3.1.0
  logging: '>=0.11.4 <0.12.0'
  markdown: ^3.0.0
  meta: ^1.2.4
  protobuf: ^2.0.0
  route_hierarchical:
    path: third_party/pkg/route.dart/
  split: ^0.0.6
  html_unescape: ^2.0.0
  sass_builder: ^2.1.0
  mdc_web: ^0.6.0
  yaml: ^2.2.0
  checked_yaml: ^1.0.0
  js: ^0.6.0
  stream_transform: ^1.2.0

dev_dependencies:
  build_runner: any
  build_test: any
  build_web_compilers: any
  collection: ^1.14.10
  git: ^2.0.0
  grinder: ^0.8.0
  json_serializable: ^3.5.0
  pedantic: ^1.11.0
  shelf: ^0.7.5
  shelf_static: ^0.2.8
  test: ^1.15.7
