name: dart_services
publish_to: none

environment:
  # Keep min SDK aligned with .travis.yml and FROM line of Dockerfile
  sdk: '>=2.3.2 <3.0.0'

dependencies:
  _discoveryapis_commons: ^0.1.8
  analyzer: ^0.36.0
  analysis_server_lib: ^0.1.4
  appengine: ^0.7.0
  args: ^1.5.2
  bazel_worker: ^0.1.21
  crypto: ^2.0.0
  dartis: ^0.3.0
  http: ^0.12.0
  logging: ^0.11.0
  path: ^1.6.2
  shelf: ^0.7.0
  rpc: ^0.6.1
  uuid: ^2.0.0
  yaml: ^2.1.15
  quiver: ^2.0.3

dev_dependencies:
  discoveryapis_generator: ^0.9.11
  async: ^2.2.0
  codemirror: ^0.5.6
  coverage: ^0.12.4
  grinder: ^0.8.0
  pedantic: ^1.7.0
  synchronized: ^2.1.0
  test: ^1.6.4
  tuneup: ^0.3.6

executables:
  services: null
