name: services
version: 0.0.1
author: Dart Team <misc@dartlang.org>
description: The server backend for a web based interactive Dart service.
homepage: https://github.com/dart-lang/dart-services
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  analysis_server:
    git:
      url: git://github.com/lukechurch/dart-analysis-server-temp-working.git
  analyzer:
    git:
      url: git://github.com/lukechurch/dart-analyzer-temp-working.git
  dart_style:
    git:
      url: git://github.com/lukechurch/dart_style.git
#  analyzer: '>=0.22.4 <0.23.0'
  appengine: '>=0.2.6 <0.3.0'
  archive: '>=1.0.19 <1.1.0'
  args: ^0.12.0
  cli_util: ^0.0.1
  # `compiler_unsupported` needs to be pegged to a specific version.
  compiler_unsupported: 1.9.3
  crypto: '>=0.9.0 <0.10.0'
  librato: '>=0.0.1 <0.1.0'
  logging: ^0.9.0
  path: ^1.3.0
  shelf: ^0.5.0
  shelf_cors: ^0.2.0
  shelf_route: ^0.11.0
  rpc: ^0.1.0
  yaml: ^2.0.0
dev_dependencies:
  _discoveryapis_commons: any
  browser: any
  codemirror: '>=0.1.0 <0.2.0'
  grinder: '>=0.7.0 <0.8.0'
  http: any
  unittest: any
executables:
  services: null
