name: dart_services
publish_to: none

environment:
  sdk: '>=2.0.0-dev.64.1 <3.0.0'

dependencies:
  _discoveryapis_commons: ^0.1.8
  analyzer: ^0.34.0
  analysis_server_lib: ^0.1.4
  appengine: ^0.6.0
  archive: ^2.0.0
  args: ^1.4.1
  crypto: ^2.0.0
  http: ^0.12.0
  logging: ^0.11.0
  path: ^1.3.0
  pedantic: ^1.4.0
  shelf: ^0.7.0
  rpc: ^0.6.1
  uuid: 2.0.0-rc1
  yaml: ^2.0.0
  quiver: ^2.0.1

dev_dependencies:
  discoveryapis_generator: ^0.9.9
  async: '>1.13.3'
  codemirror: ^0.4.0
  grinder: ^0.8.0
  test: ^1.3.0
  tuneup: ^0.3.6

executables:
  services: null
