name: dart_pad
version: 0.0.1
author: Dart Team <misc@dartlang.org>
description: The UI client for a web based interactive Dart service.
homepage: https://github.com/dart-lang/dart-pad
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  _discoveryapis_commons: '>=0.1.0 <0.2.0'
  ace: '>=0.5.10 <0.6.0'
  codemirror: '>=0.2.3 <0.3.0'
  # TODO: We need to move to a hosted (and versioned) dependency.
  comid:
    git: https://github.com/google/comid
  crypto: '>=0.9.0 <0.10.0'
  haikunator: ^0.1.0
  http: '>=0.11.1 <0.12.0'
  logging: '>=0.9.0 <0.10.0'
  markd: ">=0.7.1+4 <0.8.0"
  rate_limit: '>=0.1.0 <0.2.0'
  route_hierarchical: '>=0.6.0 <0.7.0'
dev_dependencies:
  dart_to_js_script_rewriter: any
  git: any
  grinder: '>=0.6.6+2 <0.7.0'
  http_server: ^0.9.0
  librato: '>=0.0.1 <0.1.0'
  unittest: any
  webdriver: ^0.9.0
  which: ^0.1.0
  yaml: any
dependency_overrides:
  grinder: 0.7.0-dev.2
transformers:
- dart_to_js_script_rewriter
- $dart2js:
    $exclude:
    - test/all.dart
    - web/old/playground1.dart
    - web/old/playground2.dart
    - web/packages/csslib/css.dart
