name: dart_pad
description: The UI client for a web based interactive Dart service.
homepage: https://github.com/dart-lang/dart-pad
environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  checked_yaml: ^2.0.0
  codemirror: ^0.7.3+5.65.2
  collection: ^1.15.0
  fluttering_phrases: ^0.3.1
  html_unescape: ^2.0.0
  http: ^0.13.0
  js: ^0.6.0
  json_annotation: ^4.3.0
  logging: ^1.0.0
  markdown: ^5.0.0
  mdc_web: ^0.6.0
  meta: ^1.2.4
  protobuf: ^2.0.0
  sass_builder: ^2.1.0
  split:
    path: third_party/pkg/split/
  stream_transform: ^2.0.0
  yaml: ^3.0.0

dev_dependencies:
  build_runner: ^2.0.0
  build_test: ^2.0.0
  build_web_compilers: ^3.0.0
  git: ^2.0.0
  grinder: ^0.9.0
  json_serializable: ^6.0.1
  lints: ^1.0.0
  shelf: ^1.3.0
  shelf_static: ^1.0.0
  test: ^1.20.2
  webdriver: ^3.0.0

# waiting for the next material-components-web release.
# Once released, it will need to be rolled into package:mdc_web.
#
# https://github.com/material-components/material-components-web/pull/7158
dependency_overrides:
  # `pub downgrade` will choose 8.0.0 but this conflicts in nullability with some
  # other dependency...
  built_value: ^8.1.0
  sass: 1.32.10
