name: dart_services
description: The backend service for DartPad.
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  analysis_server_lib: ^0.2.5
  analyzer: ^6.5.0
  args: ^2.5.0
  bazel_worker: ^1.1.1
  dartpad_shared: ^0.0.0
  encrypt: ^5.0.3
  google_generative_ai: ^0.4.3  
  http: ^1.2.1
  json_annotation: ^4.9.0
  logging: ^1.2.0
  meta: ^1.15.0
  path: ^1.9.0
  resp_client: ^1.2.0
  shelf: ^1.4.1
  shelf_gzip: ^4.1.0
  shelf_router: ^1.1.4
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.11
  collection: ^1.18.0
  dart_flutter_team_lints: ^3.1.0
  grinder: ^0.9.5
  json_serializable: ^6.8.0
  package_config: ^2.1.0
  shelf_router_generator: ^1.1.0
  synchronized: ^3.1.0+1
  test: ^1.25.7
  test_descriptor: ^2.0.1

dependency_overrides:
  dartpad_shared:
    path: ../dartpad_shared
