name: dart_services
publish_to: none

environment:
  sdk: ^3.1.0

dependencies:
  analysis_server_lib: ^0.2.4
  analyzer: ^5.13.0
  args: ^2.4.2
  bazel_worker: ^1.0.2
  convert: ^3.1.1
  crypto: ^3.0.3
  encrypt: ^5.0.1
  http: ^1.0.0
  logging: ^1.2.0
  meta: ^1.9.1
  path: ^1.8.3
  protobuf: ^3.0.0
  quiver: ^3.2.1
  resp_client: ^1.2.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  yaml: ^3.1.2

dev_dependencies:
  angel3_mock_request: ^8.0.0
  async: ^2.11.0
  build_runner: ^2.4.5
  dart_flutter_team_lints: ^1.0.0
  grinder: ^0.9.4
  package_config: ^2.1.0
  shelf_router_generator: ^1.0.6
  synchronized: ^3.1.0
  test: ^1.24.3
  test_descriptor: ^2.0.1

executables:
  services: null
