name: dart_services
description: The backend service for DartPad.
publish_to: none

resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  analysis_server_lib: ^0.2.5
  analyzer: ^8.4.1
  args: ^2.7.0
  bazel_worker: ^1.1.4
  dartpad_shared:
    path: ../dartpad_shared
  encrypt: ^5.0.3
  google_cloud_ai_generativelanguage_v1beta: ^0.2.0
  google_cloud_rpc: ^0.2.0
  http: ^1.6.0
  logging: ^1.3.0
  meta: ^1.17.0
  path: ^1.9.1
  resp_client: ^1.2.0
  shelf: ^1.4.2
  shelf_gzip: ^4.1.0
  shelf_router: ^1.1.4
  shelf_static: ^1.1.3
  shelf_web_socket: ^3.0.0
  web_socket_channel: ^3.0.3
  yaml: ^3.1.3

dev_dependencies:
  collection: ^1.19.1
  dart_flutter_team_lints: ^3.5.2
  grinder: ^0.9.5
  package_config: ^2.2.0
  synchronized: ^3.4.0
  test: ^1.26.3
  test_descriptor: ^2.0.2
