name: dart_services
description: The backend service for DartPad.
publish_to: none

resolution: workspace

environment:
  sdk: ^3.8.0

dependencies:
  analysis_server_lib: ^0.2.5
  analyzer: ^8.4.1
  args: ^2.7.0
  bazel_worker: ^1.1.3
  dartpad_shared:
    path: ../dartpad_shared
  encrypt: ^5.0.3
  google_cloud_ai_generativelanguage_v1beta: ^0.1.2
  google_cloud_gax: ^0.1.2
  http: ^1.3.0
  json_annotation: ^4.9.0
  logging: ^1.2.0
  meta: ^1.15.0
  path: ^1.9.0
  resp_client: ^1.2.0
  shelf: ^1.4.2
  shelf_gzip: ^4.1.0
  shelf_router: ^1.1.4
  shelf_static: ^1.1.0
  shelf_web_socket: ^3.0.0
  web_socket_channel: ^3.0.0
  yaml: ^3.1.3

dev_dependencies:
  collection: ^1.19.0
  dart_flutter_team_lints: ^3.2.1
  grinder: ^0.9.5
  json_serializable: ^6.9.5
  package_config: ^2.2.0
  synchronized: ^3.3.1
  test: ^1.25.9
  test_descriptor: ^2.0.1
