# Copyright (c) 2025, the Dart project authors.  Please see the AUTHORS file
# for details. All rights reserved. Use of this source code is governed by a
# BSD-style license that can be found in the LICENSE file.

name: dartpad_ui
description: The front-end UI of DartPad.
publish_to: none

resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  collection: ^1.19.1
  dartpad_shared:
    path: ../dartpad_shared
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.7+1
  flutter_web_plugins:
    sdk: flutter
  go_router: ^17.0.1
  google_fonts: ^6.3.3
  http: ^1.6.0
  image_picker: ^1.2.1
  json_annotation: ^4.9.0
  mime: ^2.0.0
  pointer_interceptor: ^0.10.1+2
  pretty_diff_text: ^2.1.0
  provider: ^6.1.5+1
  split_view: ^3.2.1
  url_launcher: ^6.3.2
  vtable: ^0.4.0
  web: ^1.1.1
  web_socket: ^1.0.1

dev_dependencies:
  dart_services:
    path: ../dart_services
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: ^1.26.3

flutter:
  uses-material-design: true
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/RobotoMono-Regular.ttf
        - asset: assets/RobotoMono-Bold.ttf
          weight: 700
  assets:
    - assets/dart_logo_192.png
    - assets/flame_logo_192.png
    - assets/flutter_logo_192.png
    - assets/gemini_sparkle_192.png
    - assets/prompt_suggestion_icon_darkmode.png
    - assets/prompt_suggestion_icon_lightmode.png
    - assets/firebase_studio_192.png
    - assets/hot-reload.png
