name: dartpad_shared
description: Shared code between the DartPad frontend and backend.
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  http: ^1.3.0
  json_annotation: ^4.9.0
  meta: ^1.15.0

dev_dependencies:
  build_runner: ^2.4.11
  dart_flutter_team_lints: ^3.1.0
  json_serializable: ^6.8.0
