name: samples
description: Sample code snippets for DartPad.
publish_to: 'none'

environment:
  sdk: ^3.2.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  args: ^2.4.0
  flutter_lints: ^3.0.0
  path: ^1.8.0

flutter:
  uses-material-design: true
