name: package:dart_pad

permissions: read-all

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/dart_pad.yml'
      - 'pkgs/dart_pad/**'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/dart_pad.yml'
      - 'pkgs/dart_pad/**'
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: pkgs/dart_pad/

    strategy:
      fail-fast: false
      matrix:
        include:
          - sdk: beta
          - sdk: stable

    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      - uses: dart-lang/setup-dart@d6a63dab3335f427404425de0fbfed4686d93c4f
        with:
          sdk: ${{ matrix.sdk }}
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c

      - name: Install apt dependencies
        run: sudo apt-get install -y protobuf-compiler

      - name: Install dart dependencies
        run: dart pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: dart analyze --fatal-infos

      - name: Run buildbot
        run: |
          export PATH=$PATH:$HOME/.pub-cache/bin
          dart pub global activate protoc_plugin
          dart run tool/grind.dart buildbot
