name: dart-services

on:
  # Run CI on pushes to the master branch, and on PRs against master.
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Every day at midnight

jobs:
  # Check code formatting, static analysis, and build on a single OS (linux)
  # against Dart stable and beta.
  analyze:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sdk: [stable, beta, dev, old, master]
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - uses: dart-lang/setup-dart@a57a6c04cf7d4840e88432aad6281d1e125f0d46
        with:
          sdk: stable
      - name: Install dependencies
        run: sudo apt-get install -y protobuf-compiler redis
      - name: Install dependencies
        run: dart pub get
      - name: Analyze code (example/)
        run: |
          cd example
          echo [Analyzing example]
          dart pub get
          dart analyze --fatal-infos .
      - name: Analyze code
        run: dart analyze --fatal-infos .
      - name: Prepare Flutter
        run: |
          dart run tool/update_sdk.dart ${{ matrix.sdk }}
          export PATH=$PATH:$PWD/flutter-sdks/${{ matrix.sdk }}/bin
          flutter doctor -v
          flutter config --enable-web
      - name: Run tests
        run: |
          export PATH=$PATH:$HOME/.pub-cache/bin
          dart pub global activate protoc_plugin
          ./tool/travis.sh ${{ matrix.sdk }}
