name: package:sketch_pad

permissions: read-all

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/sketch_pad.yml'
      - 'pkgs/sketch_pad/**'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/sketch_pad.yml'
      - 'pkgs/sketch_pad/**'
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: pkgs/sketch_pad/
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - uses: subosito/flutter-action@02b923c0e1a5868734f1d56fa4083c3be4f554f3
        with:
          channel: main
      - run: flutter pub get
      - run: flutter analyze
      - run: dart format --set-exit-if-changed .
      - run: flutter build web
      - run: flutter test --dart-define=SKIP_CHECK_BUILD=false
